# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'failed.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_failed(object):
    def setupUi(self, failed):
        failed.setObjectName("failed")
        failed.resize(250, 150)
        failed.setMinimumSize(QtCore.QSize(250, 150))
        failed.setMaximumSize(QtCore.QSize(250, 150))
        self.toolButton = QtWidgets.QToolButton(failed)
        self.toolButton.setGeometry(QtCore.QRect(90, 100, 70, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton.setObjectName("toolButton")
        self.label = QtWidgets.QLabel(failed)
        self.label.setGeometry(QtCore.QRect(0, 20, 251, 41))
        self.label.setStyleSheet("")
        self.label.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">连接失败!</span></p></body></html>")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")

        self.retranslateUi(failed)
        QtCore.QMetaObject.connectSlotsByName(failed)

    def retranslateUi(self, failed):
        _translate = QtCore.QCoreApplication.translate
        failed.setWindowTitle(_translate("failed", "Form"))
        self.toolButton.setText(_translate("failed", "确认"))
