# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'succeed.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_succeed(object):
    def setupUi(self, succeed):
        succeed.setObjectName("succeed")
        succeed.resize(250, 150)
        succeed.setMinimumSize(QtCore.QSize(250, 150))
        succeed.setMaximumSize(QtCore.QSize(250, 150))
        self.toolButton = QtWidgets.QToolButton(succeed)
        self.toolButton.setGeometry(QtCore.QRect(90, 110, 70, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton.setObjectName("toolButton")
        self.label = QtWidgets.QLabel(succeed)
        self.label.setGeometry(QtCore.QRect(0, 30, 251, 41))
        self.label.setStyleSheet("")
        self.label.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">连接成功!</span></p></body></html>")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")

        self.retranslateUi(succeed)
        QtCore.QMetaObject.connectSlotsByName(succeed)

    def retranslateUi(self, succeed):
        _translate = QtCore.QCoreApplication.translate
        succeed.setWindowTitle(_translate("succeed", "Form"))
        self.toolButton.setText(_translate("succeed", "确认"))
